README.md
Update Readme document
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
=> [Documentation] Update the read with gradle details

README.md
Fixing spelling mistake
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
=> [Documentation] Fixing spelling mistake

AzureCommunicationUIDemoApp/android/README.md
Added a bit more clarify on how to register android native module.
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> [Documentation] Update Android Readme

AzureCommunicationUIDemoApp/ios/Podfile
* Updated Podfile to include fixes for m1 MacBook users
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
* try follow the readme in the repo and see if you can run the iOS app in Xcode and from command line.
```
* ...
=> [Bugfix] Updated Podfile to include fixes for m1 MacBook users

README.md
Updated FAQ
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
=> [Documentation] Updated FAQ for Android debugging

README.md
* Removed FAQ section from ReadMe
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
=> [Documentation] Moved FAQ section to Wiki

AzureCommunicationUIDemoApp/App.js, AzureCommunicationUIDemoApp/android/app/src/main/java/com/azurecommunicationuidemoapp/RNAzureCommunicationUICalling.java, AzureCommunicationUIDemoApp/ios/Podfile, AzureCommunicationUIDemoApp/ios/RNAzureCommunicationUICalling.m, AzureCommunicationUIDemoApp/ios/RNAzureCommunicationUICalling.swift, README.md
added support for 1.1.0 features
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> [Feature] Added Support for Title and Subtitle

AzureCommunicationUIDemoApp/App.js, AzureCommunicationUIDemoApp/android/README.md, AzureCommunicationUIDemoApp/android/app/src/main/java/com/azurecommunicationuidemoapp/RNAzureCommunicationUICalling.java, AzureCommunicationUIDemoApp/ios/RNAzureCommunicationUICalling.m, AzureCommunicationUIDemoApp/ios/RNAzureCommunicationUICalling.swift, README.md
refactored launch parameters into - local, remote and localization options.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> [Refactor] Updated Launch Parameters

AzureCommunicationUIDemoApp/android/app/build.gradle, AzureCommunicationUIDemoApp/android/app/src/main/java/com/azurecommunicationuidemoapp/RNAzureCommunicationUICalling.java, AzureCommunicationUIDemoApp/ios/Podfile, AzureCommunicationUIDemoApp/ios/RNAzureCommunicationUICalling.m, AzureCommunicationUIDemoApp/ios/RNAzureCommunicationUICalling.swift, README.md
* Update to use Calling UI library version 1.2.0
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Update to use Calling UI library version 1.2.0

AzureCommunicationUIDemoApp/ios/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj, AzureCommunicationUIDemoApp/ios/Podfile, AzureCommunicationUIDemoApp/package.json, AzureCommunicationUIDemoApp/yarn.lock
* Version update to have iOS successful build
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> React-Native version update to support succesful build

AzureCommunicationUIDemoApp/App.js, AzureCommunicationUIDemoApp/android/app/build.gradle, AzureCommunicationUIDemoApp/android/app/src/main/java/com/azurecommunicationuidemoapp/RNAzureCommunicationUICalling.java, AzureCommunicationUIDemoApp/android/build.gradle, AzureCommunicationUIDemoApp/android/gradle.properties, AzureCommunicationUIDemoApp/android/gradle/wrapper/gradle-wrapper.properties, AzureCommunicationUIDemoApp/ios/Podfile, AzureCommunicationUIDemoApp/ios/RNAzureCommunicationUICalling.swift
* Adding orientation support for Android
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> [Calling][Feature] Adding orientation API example

demo/App.tsx, demo/android/app/build.gradle, demo/android/app/src/main/java/com/demo/RNAzureCommunicationUICalling.java, demo/ios/Podfile, demo/ios/Podfile.lock, demo/ios/RNAzureCommunicationUICalling.swift
* Release Communication UI Library API 1.9.0
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Release Communication UI Library API 1.9.0

demo/ios/RNAzureCommunicationUICalling.swift
* BugFix - rooms call join for iOS
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> [Release][BugFix] Rooms CallJoin in iOS

demo/android/README.md
- fix dead links to src code
- update line number for link to startCallComposite function
- remove unnecessary whitespace
- change bullets to code block for Mac environment variables section
Fixes GH #52 
See #52 for context
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
Try clicking all source code links in README and verify they take you to expected file (and line number if applicable)
=> doc: fix android demo README

demo/ios/RNAzureCommunicationUICalling.swift
* RCTPromise block resolving instead of reject for call composite error
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> RCTPromise block resolving instead of reject for call composite error

demo/android/app/build.gradle, demo/android/app/src/main/java/com/demo/RNAzureCommunicationUICalling.java, demo/ios/Podfile, demo/ios/Podfile.lock, demo/ios/RNAzureCommunicationUICalling.swift
* UI Library version 1.11.0-beta.2 update
* Custom title, subtitle dynamic update API implementation for Android & iOS
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Custom title, subtitle dynamic update API implementation with 1.11.0-beta.2

demo/android/app/src/main/java/com/demo/RNAzureCommunicationUICalling.java
* Keep callComposite variable for dismiss
```
[ ] Yes
[ ] No
```
```
[X] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> [BUGFIX] Keep callComposite variable for dismiss

README.md, demo/android/app/build.gradle, demo/ios/Podfile, demo/ios/Podfile.lock
* Update to 1.11.0 GA
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Update to 1.11.0 GA

README.md, demo/android/app/build.gradle, demo/ios/Podfile, demo/ios/Podfile.lock
* Update to 1.12.0 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Update Calling Library to 1.12.0 

demo/android/app/build.gradle, demo/ios/Podfile, demo/ios/Podfile.lock
* Update the ui sdk version to 1.13.0 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Update Communication services ui library version to 1.13.0
